### ISSUE TITLE
How to define geometry and other configurations

### ISSUE THREAD

**Issue by altya** [It4innovations/espreso#3]
HI, Dear espreso developer~
  
I am very interested in espreso and look forward to working on it.I tried to use ` GENERATOR` input type to build geometry and generate meshes, 

But I only found how to generate cubes. I want to know how to generate other more complex shapes. For example, in my case, I need to generate a hexagonal prism.

And,  I also don't know how to set up information such as MATERIALS. Is there an operation manual available?

Can you help me? thank you very much!

Best wishes.
Benjamin

**Comment by mec059** [comment]
Dear Benjamin,

unfortunately, the manual is still in the development. Now, the best source are exampes in the benchmark directory.

We use the generator for testing purposes only. Hence, its abilities are limited. You can generate cubes from HEXA, TETRA, PRISMA and PYRAMID (with or without mid-points). Nevertheless, the generator is able to apply a function to generated coordinates. I hope that it is sufficient for you.

The example is in the following ecf file.
[hexagonalprism.txt](https://github.com/It4innovations/espreso/files/4465353/hexagonalprism.txt)

The function that changes coordinates is set by the parameter PROJECTION_{X,Y,Z}. The function accepts old coordinates (X,Y,Z) and should return the new value (X, Y, Z according to the parameter suffix).

Here is the output of the example.
![hexagonalprism](https://user-images.githubusercontent.com/9842260/79054168-02cf1400-7c43-11ea-8e29-0ef2b784de31.png)

The example also contains a simple material settings. More examples can be found in the benchmark directory. What physics do you want to try?

Best regards,
Ondrej

**Comment by altya** [comment]
Dear Ondrej,

Thank you for your reply！
What I need to solve is a problem of **STRUCTURAL_MECHANICS_3D**.

I need to set physical information such as material density, thermal expansion coefficient, temperature, Poisson's ratio, elastic modulus, boundary conditions, etc.

I am not sure about the meaning of following variables in espreso：
- Does `EX` mean elastic modulus？
-  Does `MIXY` mean  Poisson's ratio？
- How to set `THERMAL_EXPANSION` to change with temperature ?
- `DENS` I need to set the density of steel to 7.98e-9t / mm ^ 3, how do I express the unit?
- I don't understand the meaning of `CP`.
- The standard temperature is ℃ or ℉ ？

Sorry for the delay in your precious time, I am not very familiar with this  software.
I think if there is a reference manual, it may be a lot more friendly to newcomers like me

Best regards,
Benjamin

**Comment by Brzous** [comment]
Dear Benjamin,

Thank you for your interest in the Espreso solver. Sorry for an unavailable user guide, we working on it these days. 
You are absolutely right, EX mean elastic modulus, MIXY mean Poisson’s ratio.
We use SI units, but if you set DENS to t/mm^3, you also need to set elastic modulus in GPa and your geometry must be in mm. For the temperature, we use Kelvin. 
Due to the unavailable manual, it will be better if you send us a specification of your problem (http://numbox.it4i.cz/homepage/contact-information/), and we will set up the ECF file for you. 

All the best,
Tomas

**Comment by altya** [comment]
Dear Tomas，

It's so kind of you. I will sort out the questions recently and send you an email.

Our team has done some work on espreso, but at the same time  we also have some confusion.

Looking forward to more communication with you.
Thanks again.

Best regards,
Benjamin

**Comment by altya** [comment]
Hi~
Dear Tomas @Brzous . I sent you an email a few days ago specification my problem. I want to make sure I didn't send it to the wrong email address or it went into the Bin.

Best regards,
Benjamin
