### ISSUE TITLE
Question about the C API

### ISSUE THREAD

**Issue by gkarpa** [It4innovations/espreso#5]
Hi all,

I would like to try and use espreso's FETI solver in a third party C++ project. I managed to build the library succesfully in Ubuntu 18.04 combined with some additional libraries (Intel MKL, Open-MPI, metis/parmetis, HYPRE, hdf5) and I included the API header (feti4i.h) in my project.

However, I eventually noticed (by nm *.so | grep -i FETI4I ) that the functions of the API are not contained in any of the .so that were produced by the build process. Their implementation is located in the src/omitted subfolder, which seems to be omitted during the build. My question then is, what is the intended usage of the C API? My guess is that I'm missing something, so please feel free to point me in the right direction.

Thanks a lot in advance for your time, and congratulations on your great work!

Regards,
George

**Comment by mec059** [comment]
Dear George,

implementation was in omitted folder since it was not fully updated to internal structres. Please, update your espreso repository, it contains the implementation now. In addition, ''api/apitester.cpp" and "api/example.cpp" contain inlustration of usage. 

Best Regards,
Ondrej

**Comment by gkarpa** [comment]
Dear Ondrej,

Thank you very much for the update, it links successfully now.  The examples have been a great help as well.  I will close the issue.

Best regards,
George
